name: "Java"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: "Build"
        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                java-version: [17, 21, 23]

        steps:
            - name: "Clone repository"
              uses: actions/checkout@v4

            - name: "Java Setup"
              uses: actions/setup-java@v4
              with:
                distribution: "temurin"
                java-version: ${{ matrix.java-version }}
                cache: "gradle"

            - name: "Build project"
              run: ./gradlew build
