name: "Java"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: "Build"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Clone repository"
              uses: actions/checkout@v4