name: "Java"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: "Build"
        runs-on: "ubuntu-latest"

        # matrix of java versions
        strategy:
            matrix:
                java-version: [8, 17, 21 ,23]

        steps:
            - name: "Clone repository"
              uses: actions/checkout@v4

            - name: "Java setup"
              uses: actions/setup-java@v4
              with:
                distribution: "temurin"
                java-version: ${{ matrix.java-version }}

            - name: "Build project"
              run: ./gradlew build

            - name: "Produce distribution"
              run: ./gradlew distZip

            - name: "Upload artifact"
              uses: actions/upload-artifact@v4
              with:
                path: build/distribution/SSH.zip
                name: ssh-java-${{ matrix.java-version }}